import SSDLogo from './../../assets/images/SSD.webp';
import DCRFLogo from './../../assets/images/dcrf.webp';
import HectorPic from './../../assets/images/hector.webp';
import ProfilePic from './../../assets/images/ProfilePic.webp';
import DatabasePic from './../../assets/images/database.webp';
import KnightHackLogo from './../../assets/images/knighthack.jpg';
import InspirationPic from './../../assets/images/inspiration.jpg';

export default [
  {
    "_id": 1,
    "tools": "MERN Stack web app",
    "headerText": "DC Rock Fitness",
    "subText": ["(No longer functional) A website for a fitness center where an admin can create ","blog posts"," and nutrition posts. Clients can view their assigned ", " personalized workout"," plans for the week."],
    "link": "dcrf.ericnavar.com",
    "image": DCRFLogo,
    "altLabel": "DC Rock Fitness Logo",
    "ariaLabel": "DC Rock Fitness website"
  },
  {
    "_id": 5,
    "tools": "React app",
    "headerText": "My Resume",
    "subText": ["My resume but with way more CSS than it needs to have and now with dark mode 😎"],
    "link": "/portfolio",
    "image": ProfilePic,
    "altLabel": "Eric Navar",
    "ariaLabel": "Eric Navar resume"
  },
  {
    "_id": 4,
    "tools": "React app",
    "headerText": "Inspiration Generator",
    "subText": ["Autogenerated ","inspiration"," with each refresh!"],
    "link": "/inspire",
    "image": InspirationPic,
    "altLabel": "Mountain",
    "ariaLabel": "Inspiration Generator"
  },
  {
    "_id": 3,
    "tools": "React app",
    "headerText": "Society of Software Developers",
    "subText": ["A new home page I helped make for Society of Software Developers for which I'm the VP. It will go online soon."],
    "link": "https://ssd.ericnavar.com",
    "image": SSDLogo,
    "altLabel": "SSD Logo",
    "ariaLabel": "SSD Website"
  },
  {
    "_id": 2,
    "tools": "Flask app",
    "headerText": "SQL Injection Playground",
    "subText": ["A ","flask app"," I got running that serves as an example for how ","SQL injection"," in a website with poor security may occur"],
    "link": "https://sql-ssd.herokuapp.com/login",
    "image": DatabasePic,
    "altLabel": "Database icon",
    "ariaLabel": "SWL injection playground"
  },
  {
    "_id": 6,
    "tools": "HTML, CSS",
    "headerText": "Someone else's portfolio",
    "subText": ["This website is ","not good"," at all so I don't know why I linked it. I just wanted to help out Hector."],
    "link": "http://hectorrizo.com",
    "image": HectorPic,
    "altLabel": "Hector Rizo",
    "ariaLabel": "Hector Rizo's portfolio"
  },
  {
    "_id": 7,
    "tools": "HTML, CSS",
    "headerText": "How to Win a Hackathon",
    "subText": ["A guide on how to win a hackathon that is ","100% guaranteed"," to work. This was my submission for ","Knight Hacks"],
    "link": "http://knighthack.com",
    "image": KnightHackLogo,
    "altLabel": "Knight Hack Logo",
    "ariaLabel": "How to win a hackathon"
  }
]