import DCRFLogo from './../assets/projects/dcrf.webp';
import InspirationPic from './../assets/projects/inspiration.webp';
import SimplifunctionLogo from './../assets/projects/simplifunction.webp';
import WebIcon from '../assets/icons/web_fluent';
import { Project } from '../commonTypes';

const projectData:Array<Project> = [
  {
    _id: 3,
    tools: 'React app',
    headerText: 'Inspiration Generator',
    subText: [['Autogenerated ', 'inspiration', ' with each refresh!']],
    image: InspirationPic,
    altLabel: 'Mountain',
    ariaLabel: 'Inspiration Generator',
    links: [
      {
        label:'Website',
        ariaLabel: 'Inspiration Generator',
        hyperlink: '/inspire',
        icon: WebIcon
      },
    ]
  },
  {
    _id: 7,
    tools: '',
    headerText: 'SimpliFunction',
    subText: [['Website that allows users to create formulas for Microsoft Excel and Google Sheets without needing to know Visual Basic For Applications syntax or any programming.']
    ],
    image: SimplifunctionLogo,
    altLabel: 'Simplifunction Logo',
    ariaLabel: 'Simplifunction website',
    links: [
      {
        label:'Website',
        ariaLabel: 'Simplifunction Logo',
        hyperlink: 'https://www.simplifunction.com',
        icon: WebIcon
      },
    ]
  },
  {
    _id: 1,
    tools: 'MERN Stack web app',
    headerText: 'DC Rock Fitness',
    subText: [['(NO LONGER FUNCTIONAL)'],
      ['A website for a fitness center where an admin can create ',
        'blog posts', ' and nutrition posts. Clients can view their assigned ',
        ' personalized workout', ' plans for the week.']
    ],
    image: DCRFLogo,
    altLabel: 'DC Rock Fitness Logo',
    ariaLabel: 'DC Rock Fitness website',
    links: [
      {
        label:'Website',
        ariaLabel: 'DC Rock Fitness Website',
        hyperlink: 'https://dcrf.ericnavar.com/',
        icon: WebIcon
      }
    ]
  },
];

export { projectData };
